function isoOffsetDays(offsetDays) {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString();
}

function dateOnlyOffsetDays(offsetDays) {
  return isoOffsetDays(offsetDays).slice(0, 10);
}

export function createDemoState() {
  const now = new Date().toISOString();
  const positionId = "demo-position-0700";
  const reviewId = "demo-review-1";

  return {
    macroFramework: {
      summary: "当前先按均衡偏防守处理。大方向不追风险资产，高弹性仓位以试错和验证为主。",
      marketStance: "balanced",
      liquidityView: "neutral",
      ratesView: "sideways",
      riskAppetite: "neutral",
      policyView: "政策偏托底但弹性不均，汇率与利率没有形成明确顺风。",
      portfolioPlaybook: "总仓位保持克制，优先现金流稳定、估值不过分、逻辑能验证的方向。",
      focusAreas: "互联网平台、AI 基础设施、现金流稳健龙头。",
      avoidAreas: "纯题材高弹性、缺少盈利支撑的小票。",
      invalidation: "若流动性明显转宽且风险偏好持续回升，可把框架上调为偏进攻。",
      reviewDate: dateOnlyOffsetDays(3),
      updatedAt: isoOffsetDays(-1),
    },
    constitution: {
      goal: "Protect downside first, compound only on validated ideas / 先守住回撤，再在验证过的逻辑上复利",
      style: "Thesis-driven medium-term positions / 以 thesis 驱动的中线持仓",
      competence: "Only act when catalyst, invalidation, and holding horizon are all explicit / 只有在催化、失效条件、持有周期都说清时才行动",
      bans: "No FOMO, no revenge trades, no thesis-free positions / 禁止追涨、报复性交易、无 thesis 建仓",
      coreMax: 15,
      probeMax: 5,
      themeMax: 30,
      lastEditedAt: now,
    },
    rules: {
      singlePositionWarn: 15,
      largeReallocation: 5,
      allowInstrumentMismatch: true,
      missingTargetWeightAction: "warn",
    },
    positions: [
      {
        id: positionId,
        ticker: "0700",
        name: "Tencent",
        market: "HK",
        theme: "AI infrastructure",
        industryViewId: "demo-industry-aiinfra",
        instrumentType: "single_stock",
        positionType: "core_midterm",
        inCompetenceCircle: true,
        shareCount: 300,
        marketValue: 114000,
        lastPrice: 380,
        avgCost: 332,
        portfolioWeight: 0.14,
        maxWeightAllowed: 0.15,
        thesisHorizonLabel: "midterm",
        entryReasonSummary: "核心逻辑是广告与游戏现金流稳定，AI 应用与云业务有改善空间。",
        exitInvalidatorsSummary: "监管重新收紧、核心业务增速持续下滑，或资本开支显著挤压自由现金流。",
      },
      {
        id: "demo-position-9988",
        ticker: "9988",
        name: "Alibaba",
        market: "HK",
        theme: "China platform",
        industryViewId: "demo-industry-platform",
        instrumentType: "single_stock",
        positionType: "probe",
        inCompetenceCircle: true,
        shareCount: 200,
        marketValue: 15600,
        lastPrice: 78,
        avgCost: 82,
        portfolioWeight: 0.03,
        maxWeightAllowed: 0.05,
        thesisHorizonLabel: "midterm",
        entryReasonSummary: "试错仓，观察电商利润率修复和资本分配纪律是否延续。",
        exitInvalidatorsSummary: "利润率改善停滞，或回购纪律明显弱化。",
      },
    ],
    industryViews: [
      {
        id: "demo-industry-platform",
        name: "中国互联网平台",
        status: "observe",
        cycle: "stabilizing",
        thesis: "利润率修复与回购纪律改善，但需求和估值扩张仍需验证。",
        keySignals: "电商 take rate、回购执行、云业务利润率。",
        conclusion: "维持观察，允许小仓位验证，不适合大幅进攻。",
        risks: "消费走弱、监管口径变化、云业务恢复不及预期。",
        invalidation: "若利润率改善中断且回购弱化，转入回避。",
        reviewDate: dateOnlyOffsetDays(5),
        relatedTickers: "9988, BABA",
        updatedAt: isoOffsetDays(-2),
      },
      {
        id: "demo-industry-aiinfra",
        name: "AI 基础设施",
        status: "tailwind",
        cycle: "upcycle",
        thesis: "资本开支与算力需求仍在扩张，龙头公司具备更强兑现能力。",
        keySignals: "云厂商 capex、GPU 供需、订单能见度。",
        conclusion: "可继续跟踪并在回撤时复核机会，但需要防估值过热。",
        risks: "估值过高、订单前置透支、capex 节奏变化。",
        invalidation: "若 capex 明显下修且供给宽松，顺风状态失效。",
        reviewDate: dateOnlyOffsetDays(-1),
        relatedTickers: "0700, NVDA",
        updatedAt: isoOffsetDays(-3),
      },
    ],
    thesisSnapshots: [
      {
        id: "demo-snapshot-0700",
        positionId,
        ticker: "0700",
        title: "0700 thesis snapshot",
        thesisSummary: "广告、游戏与 AI 相关投入形成中期再加速预期。",
        catalystSummary: "季度业绩超预期，AI 应用商业化推进。",
        invalidationSummary: "游戏与广告双双低于预期，同时资本开支明显侵蚀利润。",
        horizonLabel: "midterm",
        evidenceList: [],
        notes: "适合作为中线核心仓位，但需要控制主题集中度。",
        snapshotDate: isoOffsetDays(-9),
        createdAt: isoOffsetDays(-9),
      },
    ],
    watchlist: [
      {
        id: "demo-watch-baba",
        ticker: "BABA",
        name: "Alibaba ADR",
        market: "US",
        source: "manual",
        thesis: "若回购持续、云业务改善确认，可考虑从观察名单进入正式审查。",
        catalyst: "季度业绩、资本配置、云业务指引。",
        addedAt: isoOffsetDays(-5),
      },
      {
        id: "demo-watch-tsla",
        ticker: "TSLA",
        name: "Tesla",
        market: "US",
        source: "manual",
        thesis: "仍需继续观察需求韧性和利润率，暂不进入正式交易审查。",
        catalyst: "交付数据、毛利率、FSD 进展。",
        addedAt: isoOffsetDays(-2),
      },
    ],
    reviews: [
      {
        id: "demo-review-memory-1",
        positionId,
        positionName: "0700 Tencent",
        tradeAction: "reduce",
        resultQuality: "delay",
        followedAgent: true,
        reviewDate: dateOnlyOffsetDays(-1),
        actionReview: "原计划减仓过快，后来复盘发现更多是因为短期波动放大了不安感。",
        reason: "同主题仓位偏高，且减仓时点更多是情绪驱动而不是 thesis 失效。",
        mistakeTags: ["仓位过重", "情绪化卖出"],
        lesson: "先检查 thesis 是否被证伪，再决定是否减仓；主题集中度高时要提前规划分步处理。",
        reviewPayload: null,
        createdAt: isoOffsetDays(-1),
      },
    ],
    tradeReviewRecords: [
      {
        id: "demo-trade-record-1",
        positionId,
        thesisSnapshotId: "demo-snapshot-0700",
        reviewTargetType: "position",
        reviewStage: "post_trade",
        actionLabel: "buy",
        finalAction: "delay",
        matchedRules: [
          { id: "R000_watchlist_before_execution", message: "新标的应先进入观察池，再进入正式交易审查。" },
          { id: "R002_missing_invalidator", message: "未定义失效条件，不能判断何时该退出。" },
        ],
        decisionSummary: "新标的尚未完成观察，且退出条件不清晰，因此应延后复核而不是直接执行。",
        agentSummary: "",
        userNote: "想趁回调先试一笔，但准备还不够完整。",
        executed: true,
        executionNote: "先保持观察，不急于下单。",
        outcomeLabel: "delay",
        createdAt: isoOffsetDays(-1),
      },
    ],
    behaviorProfiles: [
      {
        id: "demo-profile-1",
        profileKey: "large_reallocation",
        profileName: "大幅调仓倾向",
        profileSummary: "一旦判断反转，容易一次性做大幅仓位调整，需加入冷静期。",
        signalCount: 2,
        severity: "medium",
        evidenceList: [],
        updatedAt: isoOffsetDays(-1),
      },
    ],
    lastReview: {
      id: reviewId,
      reviewInput: {
        positionId: "__new__",
        newTicker: "BABA",
        newName: "Alibaba ADR",
        tradeAction: "buy",
        targetPositionType: "probe",
        targetWeightAfterTrade: "4",
        emotionRisk: "medium",
        thesisStatus: "active",
        triggerType: "manual",
        plannedHoldingDays: "60",
        reviewDueAt: "",
        sameThemeWeight: "18",
        cooldownUntil: "",
        referencePrice: "72",
        whyNow: "回购延续、估值压缩较多，考虑先建立试错仓。",
        thesisReference: "平台业务利润率改善，云业务边际修复。",
        whatChanged: "市场情绪转弱后重新回到观察名单处理。",
        wrongIf: "利润率修复失败，或云业务再度走弱。",
        holdingPlanAfterTrade: "若逻辑确认再逐步加仓，否则维持观察。",
        alternativeAction: "先继续观察一个业绩周期。",
      },
      positionName: "BABA Alibaba ADR",
      result: {
        finalAction: "delay",
        disciplineScore: 82,
        delayWindow: "7d",
        matchedRules: [
          { id: "R000_watchlist_before_execution", message: "新标的应先进入观察池，再进入正式交易审查。" },
          { id: "R002_missing_invalidator", message: "未定义失效条件，不能判断何时该退出。" },
        ],
        why: "当前更适合继续观察，而不是立刻执行。",
        requiredNextStep: "先加入观察池并补全失效条件。",
        riskFlags: ["not_on_watchlist", "missing_invalidator"],
      },
      agentReview: {
        mode: "demo",
        text: [
          "Investment Committee Pre-trade Memo / 投前纪要",
          "投资结论 / Investment Conclusion: 延后复核 / Delay and Reassess",
          "观察状态 / Observation Status: 当前仍处于观察名单阶段，尚不适合直接建仓。 / The idea is still in observation and is not ready for execution.",
          "核心依据 / Core Basis: 初始 thesis 有吸引力，但退出条件仍不完整。",
          "关键风险 / Key Risks:",
          "中文：尚未完成观察期，且失效条件不够明确。",
          "English: The setup has not completed its watchlist period and invalidation conditions remain unclear.",
          "下一步动作 / Next Step:",
          "中文：继续观察一个财报周期，并写清楚什么事实会推翻当前判断。",
          "English: Keep the name on the watchlist through the next earnings cycle and define explicit invalidation triggers.",
        ].join("\n"),
      },
      agentReflection: {
        mode: "demo",
        text: [
          "Investment Committee Post-trade Memo / 投后复盘纪要",
          "原因归纳 / Core Reason:",
          "中文：这次没有直接执行是正确的，因为观察和退出规则都还不完整。",
          "English: It was correct not to proceed because both observation work and exit rules were incomplete.",
          "后续改进 / Improvement Focus:",
          "中文：以后新标的统一先过观察名单，再进入正式仓位讨论。",
          "English: Standardize watchlist-first review for every new idea before discussing position sizing.",
        ].join("\n"),
        suggestedReason: "原因归纳 / Core Reason\n中文：当时的主要问题不是价格，而是准备工作不完整。\nEnglish: The main issue was not price but incomplete preparation.",
        suggestedTags: ["无thesis交易", "失效条件不清"],
        suggestedLesson: "复盘教训 / Lesson\n中文：先观察、再交易；先定义退出、再谈加仓。\nEnglish: Observe before trading, and define exit conditions before adding size.",
      },
    },
    events: [
      {
        id: "demo-event-1",
        title: "Demo loaded",
        detail: "Public demo mode is using sample investment records.",
        severity: "info",
        createdAt: isoOffsetDays(-1),
      },
      {
        id: "demo-event-2",
        title: "Watchlist reminder",
        detail: "BABA is close to the end of its observation window and can move to review next.",
        severity: "info",
        createdAt: isoOffsetDays(-2),
      },
    ],
  };
}
